@baseUrl = http://localhost:3003

###
GET {{baseUrl}}/api/blogs

###
PUT {{baseUrl}}/api/blogs/a
Content-Type: application/json

{
  "title": "Test",
  "author": "Aaron",
  "url": "www.atkinsio.com",
  "likes": 10
}
