@baseUrl = http://localhost:3003

###
GET {{baseUrl}}/api/blogs

###
POST {{baseUrl}}/api/blogs
Content-Type: application/json

{
  "title": "Test",
  "author": "Aaron",
  "url": "www.atkinsio.com",
  "userId": "5e893de1b7eda3177367ce0a"
}
###
GET {{baseUrl}}/api/users

###
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "username": "aaron",
  "name": "Aaron2",
  "password": "secret"
}
###
POST {{baseUrl}}/api/login
Content-Type: application/json

{
  "username": "aaron",
  "password": "secret"
}
