@baseUrl = http://localhost:3003

###
GET {{baseUrl}}/api/blogs

###
POST {{baseUrl}}/api/blogs
Content-Type: application/json

{
  "title": "Test",
  "author": "Aaron",
  "url": "www.atkinsio.com"
}
###
GET {{baseUrl}}/api/users

###
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "username": "Aaron",
  "name": "Aaron2",
  "password": "secret"
}
